### PR TITLE
EWLJ-309 Adding multiselect search-sort

### PR DESCRIPTION
**Pull request by shaal**
## Ticket(s)

Please do not submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Jira Ticket**

- [EWLJ-309: Design a sort drop down to search results page (https://issues.ama-assn.org/browse/EWLJ-309)

## Description
In the current styleguide there is a component that is based on `chosen` javascript-library (that was not working for what was needed)

I replaced the component with `multiselect` of jquery-ui (which is the way it was done in AMA styleguide)

## To Test
- [ ] Switch your JOE SG2 branch to `feature/EWLJ-309-sort-dropdown-for-search-results-page`
- [ ] Run gulp serve
- [ ] Go to http://localhost:3000/?p=atoms-select-menu
- [ ] Check that the `select menu` is themed
- [ ] Go to http://localhost:3000/?p=pages-search-results
- [ ] Check that the drop-down sort in search bar is themed
- [ ] Try different browser widths
- [ ] Check that the size of each element of the search bar is positioned correctly

## Relevant Screenshots/GIFs
image

### CODE REVIEW

**Comment by designerneil** [comment]
@shaal can you explain why jQuery UI was used instead of Chosen in more detail?

**Comment by designerneil** [comment]
@shaal can we try to use Chosen instead of jQuery UI? If you need a select without the search just pass this parameter `jQuery('select').chosen( {disable_search: true} );`

**Comment by shaal** [comment]
> @shaal can we try to use Chosen instead of jQuery UI? If you need a select without the search just pass this parameter `jQuery('select').chosen( {disable_search: true} );`

I reverted the jquery-ui changes on that branch, reset it to `develop`, and then added the chosen to sort-by dropdown in search page (also changed the background color of dropdown from blue to the same purple color that is on that page)

**Comment by designerneil** [comment]
@shaal great job. I just have a couple style changes needed before approving.

Pattern_Lab_-_pages-search-results


The select should match this: 
Screen Shot 2019-04-17 at 10 28 05 AM

**Comment by shaal** [comment]
@designerneil I applied the changes you requested. Can you please review it again?

**Pull request merged**
