### PR TITLE
EWLJ-406: Restructure image expander

### PR DESCRIPTION
**Pull request by nstriedinger**
**Jira Ticket**

- https://issues.ama-assn.org/browse/EWLJ-406

## Description

Restructure image expander. 

## To Test

- [ ] Click on image here -- `http://localhost:3000/?p=pages-article`
- [ ] Visit `http://ama-joe.local/article/what-historical-ideals-womens-shapes-teach-us-about-womens-self-perception-and-body-decisions-today/2019-10`

### CODE REVIEW

**Comment by designerneil** [comment]
@nstriedinger can change the cursor to a pointer on hover for the close button so a user knows they can click it?

**Comment by designerneil** [comment]
@nstriedinger how do I test this in D8? I figured it out. In the future please provide instructions on how to test a PR in styleguide and D8. 

I had to visit 
http://ama-joe.local/article/what-historical-ideals-womens-shapes-teach-us-about-womens-self-perception-and-body-decisions-today/2019-10 to check the enlarge image feature

**Comment by designerneil** [comment]
@nstriedinger when I upload an image to get expanded there is no mechanism to keep it from filling the whole screen which pushes the close button out of the viewport 
Screen Shot 2019-11-08 at 11 13 17 AM
Screen Shot 2019-11-08 at 11 13 10 AM

**Comment by nstriedinger** [comment]
@designerneil Are you talking about viewing this page? `http://ama-joe.local/article/what-historical-ideals-womens-shapes-teach-us-about-womens-self-perception-and-body-decisions-today/2019-10`

**Comment by nstriedinger** [comment]
@designerneil Do you think `  width: 96%;` would be better for  **is-zoomed**
`<figure class="joe__inline-image joe__inline-image--center is-zoomed">`

**Comment by designerneil** [comment]
> @designerneil Do you think ` width: 96%;` would be better for **is-zoomed**
> `<figure class="joe__inline-image joe__inline-image--center is-zoomed">`

As long as the X stays on page on desktop and mobile

**Comment by designerneil** [comment]
@nstriedinger here's the problem. When I upload an image with a white background I no longer see the X button
Screen Shot 2019-11-08 at 2 44 22 PM

**Comment by designerneil** [comment]
@nstriedinger the max-width is still too wide causing the page to have scrollbars

This is what is being returned

` element.style {
  max-width: 1770px;
}`

**Comment by designerneil** [comment]
@nstriedinger that worked but you need to set the x and y for absolute positioned elements. Please the x position to 0 and y to auto

**Pull request merged**
