### PR TITLE
EWLJ-338 Adds reference tooltip

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**

- [EWLJ-338: SG | Design popup references to articles](https://issues.ama-assn.org/browse/EWLJ-338)

## Description

Add tooltips to article <sup> tags using reference information below the article.

## To Test
- [ ] switch your JOE styleguide branch to `feature/EWLJ-338-popup-reference-articles`
- [ ] run `gulp serve`
- [ ] switch your D8 branch to `feature/EWLJ-338-popup-reference-articles`
- [ ] enable local JOE styleguide development in your local.yml file in D8
- [ ] run `scripts/build` outside of your vagrant
- [ ] `vagrant ssh` > `drush @joe.local cr`
- [ ] visit http://ama-joe.local/article/making-policy-augmented-intelligence-health-care/2019-02
- [ ] hover over a superscript text with a number in it
- [ ] observe a tooltip appears with the relevant reference in it 

## Visual Regressions
The repo does not use a visual regression testing system.

## Relevant Screenshots/GIFs

screen shot 2019-02-05 at 3 24 35 pm

## Remaining Tasks

n/a

## Additional Notes

n/a

### CODE REVIEW

**Review by russom-woldezghi — CHANGES_REQUESTED** [review]
Can you add `js/resource-tooltips.js: {}` to `ama_joe_theme.libraries.yml` file for the tooltip js to load? I wasn't able to get it working without adding that. Let me know if there was another way to get the js file to load.

**Comment by designerneil** [comment]
@russom-woldezghi the js/resource-tooltips.js is compiled in the Joe styleguide in the build.config

**Comment by designerneil** [comment]
Please make sure you have local JOE styleguide running in your local.yml

**Review by russom-woldezghi — APPROVED** [review]

**Comment by russom-woldezghi** [comment]
Looks good (referencing https://github.com/AmericanMedicalAssociation/ama-d8/pull/1268 as dependency)

**Review by mrspete — APPROVED** [review]
So nice!!!

**Pull request merged**
