### PR TITLE
EWLJ-440: Add art gallery image

### PR DESCRIPTION
**Pull request by nstriedinger**
**Jira Ticket**

- https://issues.ama-assn.org/browse/EWLJ-440

## Description

Add Art Gallery page Hero image

## Test
This adds a Header Image to https://joe-test.ama-assn.org/art-gallery. Like the other `Main Nav` images (/issues, /articles, /cases, /podcasts, /cme)

1. Verify `art-gallery` has this header image.

With the same pattern as below.
Screen Shot 2019-11-06 at 12 40 12 PM

### CODE REVIEW

**Comment by designerneil** [comment]
@nstriedinger I have no idea how to test this PR

**Comment by designerneil** [comment]
@nstriedinger how do I test this in D8? I load the art page but don't get an image
Screen Shot 2019-11-08 at 11 32 41 AM

**Comment by nstriedinger** [comment]
@designerneil Pardon, can you use this branch on the D8 end?

https://github.com/AmericanMedicalAssociation/ama-d8/pull/1680

**Review by designerneil — APPROVED** [review]
i see a background image now

**Pull request merged**
