### PR TITLE
EWLJ-784: Modified caption field position on Mobile devices.

### PR DESCRIPTION
**Pull request by jorge-melo**
## JIRA Ticket(s)

- See ticket [EWLJ-784](https://ama-it.atlassian.net/jira/software/c/projects/EWLJ/boards/357?selectedIssue=EWLJ-784).

## Description

Caption placement for Featured Image component on Desktop versus Tablet/Mobile.}

Given: Individual has accessed JOE website When the user accesses the website through a tablet or mobile device Then they should be able to view the captions for all Featured Image layout types centered **below the image**.

## Testing instructions

1. Run "lando gulp" at styleguide/joe-style-guide/styleguide
2. Create a "Feature image" on the "Ethics Close Up" content type.
3. `Test mobile and tablet displays`.
4. Caption field should be below the image.

## Relevant Screenshots/gifs:
Mobile
Screenshot 2024-10-18 at 11-42-11 EWLJ-784 Journal of Ethics American Medical Association

Tablet
Screenshot 2024-10-18 at 11-41-47 EWLJ-784 Journal of Ethics American Medical Association

[EWLJ-784]: https://ama-it.atlassian.net/browse/EWLJ-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by isa-ama** [comment]
Compare with the layout Image on Left, the Space between Image and caption are not the same. Make sure the space is the same on both layouts.

spaceaboveIR

**Review by isa-ama — CHANGES_REQUESTED** [review]
The image is too close to the caption. Check the screenshot.

**Comment by isa-ama** [comment]
Looks good!

leftandright

**Review by rgb-ama — APPROVED** [review]
approved

**Review by isa-ama — APPROVED** [review]

**Pull request merged**
