### PR TITLE
EWLJ-345 email sign up design

### PR DESCRIPTION
**Pull request by aCyborg**
## Ticket(s)

**Github Issue**
n/A

**Jira Ticket**

- [EWLJ-345: Email Sign Up Design](https://issues.ama-assn.org/browse/EWLJ-345)
- [EWLJ-337: Ability to have more than one CTA box.](https://issues.ama-assn.org/browse/EWLJ-337)

## Description

Creation of a secondary CTA design style (rail cta secondary) as well as a rail form molecule with default and secondary styles.

This work created:

- Rail CTA Secondary Molecule
- Rail Form Molecule
- Rail Form Secondary Molecule.

This work modified:
- Article No Image Page (rail)
- Homepage Page (cta band)
- CTA Band Organism

## To Test

- [ ] Build the styleguide locally.
- [ ] Review the Rail CTA Secondary Molecule for markup, styles, responsiveness, and accessibility.
- [ ] Review the Rail Form Molecule for markup, styles, responsiveness, and accessibility.
- [ ] Review the Rail Form Secondary Molecule for markup, styles, responsiveness, and accessibility.
- [ ] Review the CTA Band Organism.
- [ ] Review the Article No Image Page, verify that there are more than one CTA boxes on the page.
- [ ] Review the Homepage Page.

## Visual Regressions

N/A

## Relevant Screenshots/GIFs

The following Screenshots were approved by the JoE Team with the note to remove the rule.

form-style

## Remaining Tasks

N/A

## Additional Notes

N/A

### CODE REVIEW

**Comment by designerneil** [comment]
@aCyborg EWL-345: Email Sign Up Design links to a story with a title "Article Content - Add Short Description Field to Article Content Type"

EWL-337: Ability to have more than one CTA box. Links to: Configure IA in Drupal for AMA Wire Site

Are these correct?

**Comment by designerneil** [comment]
In orders to test this PR effectively I will need a mockup or something to reference. Perhaps a screenshot?

**Comment by designerneil** [comment]
Just updated the links in this PR to point to the correct Jira story

**Comment by designerneil** [comment]
@aCyborg are there mockups you are using to create the email sign design?

**Comment by designerneil** [comment]
Pattern_Lab_-_pages-homepage

**Comment by aCyborg** [comment]
Sorry for the confusion Neil, didn't cross my mind to double check the beginnings of the link in the template.

I've updated the cta band box heights at tablet size and added the comps that were approved by the client.

Let me know if you have any additional questions for me.

**Pull request merged**
