### PR TITLE
EWLJ-316: Ethics polls buttons should look the same as style guide

### PR DESCRIPTION
**Pull request by adriansmuresan**
## JIRA Ticket(s)
- [EWLJ-316: Ethics polls buttons should look the same as style guide](https://issues.ama-assn.org/browse/EWLJ-316)

## Description:
- Adds the appropriate classes do the buttons in order to match the styleguide.
- Adds styling for button and show/hide text

## To Test:
- [ ] run `gulp serve`
- [ ] enable local SG2 testing in your D8 env
- [ ] in your D8 instance run `drush @joe.local cr`
- [ ] Navigate to (http://ama-joe.local/home) and check that the styling of the buttons on the poll forms  matches the styleguide(http://localhost:3002/?p=organisms-poll--structured)

## Automated Test:
N/A

## Style Guide:
N/A

## Relevant Screenshots/GIFs:
N/A

## Additional Notes:
Anything more to add?

---

[Pull Request Guidelines](https://github.com/palantirnet/development_documentation/blob/master/guidelines/pr_review.md)

### CODE REVIEW

**Comment by adriansmuresan** [comment]
This ticket needs more work as the javascript from the `poll-reveal.js` from the styleguide is not working on the drupal side. We are adding the `is-open` and `is-active` classes that control the poll in the ama-joe-helper module. There may be some drupaly things that the poll module is doing as the `SHOW RESULTS` and `HIDE RESULTS` are input fields of `type=submit` that seems to reload the page when pressed.

**Comment by adriansmuresan** [comment]
This has a dependency in the ama-d8 repo, PR here: https://github.com/AmericanMedicalAssociation/ama-d8/pull/1229

**Comment by mrspete** [comment]
The style on this looks fine. There a still a couple changes on the drupal side, but I will update the issue there.

**Review by mrspete — APPROVED** [review]
the SG side looks good

**Pull request merged**
